### ISSUE TITLE
Better opus.map for versioning

### ISSUE THREAD

**Issue by janreges** [imarc/opus#10]
Hi Matthew,

your OPUS package is great and it make great job in our internal framework! Thank you for it! 👍 

In our workflow, we need to versioning opus.map, because here are many developers working with composer and our packages, which almost every uses OPUS.

Without versioning/sharing opus.map between developers, every developer have to resolve conflict, which was already resolved by another developer. So, we are versioning opus.map and it works well.

Just one issue with it is, that sometime, when OPUS was running but no changes were detected, despite this, opus.map is regenerated with small change. And then, obviously, there are lot of conflicts in opus.map in GIT.

As you can see below, only one row has been moved to the end of an array.

Is it necessary also in this case?

Thank you for your response :)

```
index 6f0773a..a1c6435 100644
--- a/opus.map
+++ b/opus.map
@@ -267,10 +267,10 @@
         "65": "siteone-cms/admin-forms",
         "66": "siteone-cms/datagrid",
         "67": "siteone-webcore/database-model-generator",
-        "68": "siteone-webcore/database",
         "69": "siteone-cms/users-basic",
         "70": "siteone-cms/cms",
-        "71": "siteone-webcore/url-http-authentication"
+        "71": "siteone-webcore/url-http-authentication",
+        "72": "siteone-webcore/database"
     },
     "/app/config/admin-forms.neon": [
         "siteone-cms/admin-forms"
```

**Comment by mattsah** [comment]
Thanks, I'm glad you find the package/system useful.

A few things...

1. The fact that Opus is using numeric indexing apparently typed as strings like this could probably be considered a bug.  If I'm understanding the context of the diff correctly this is the section of the map where Opus identifies which packages provide a given file.  It should not need any particular indexes (numeric or strings) for this and it should simply be an array of strings (package names).

2. You may want to rethink/restructure packages if you have that many packages providing the same file.

3. If the numeric indexing can be treated as a bug, then I suspect simply sorting the array by values would resolve it, as that would keep each value in its place unless one was added or removed.

Does this make sense?  To get more clarity though, is it possible for you to provide both versions of the opus.map which are being diffed (or an equivalent)?

**Comment by janreges** [comment]
Thank you for your answer, Matthew :)

Yes, it's first part of JSON, where a key is folder or file, and value is array/object with numeric indexes.

One file have to be only on one package (it's OK), but in opus.map are also directories, not only files. And issue is order in array and numeric indexes inside directories, like an "/app" in example below.

So when it's possible to remove numeric indexes and sort packages by name (for example in "/app" below), it would be great!

If it's not so clear, i can send you an e-mail with two opus.map files (with formatted JSON for compare).

Thank you.

```json
{
    "/app": {
        "10": "siteone-cms/pools",
        "13": "siteone-cms/package-descriptor",
        "14": "siteone-webcore/package-descriptor",
        "16": "siteone-webcore/image-generator",
        "19": "siteone-webcore/common",
        "20": "siteone-cms/users-basic",
        "21": "siteone-webcore/url-http-authentication",
        "22": "siteone-webcore/file-to-text",
        "6": "siteone-cms/cms-module-generator",
        "7": "siteone-cms/enumerations",
        "9": "siteone-cms/files"
    },
    "/app/_AdminModule": {
        "10": "siteone-cms/enumerations",
        "12": "siteone-cms/files",
        "13": "siteone-cms/pools",
        "17": "siteone-cms/users-basic",
        "18": "siteone-cms/cms",
        "9": "siteone-cms/cms-module-generator"
    }
    ...
     "/app/_AdminModule/presenters/templates/@layout.latte": [
        "siteone-cms/cms"
    ],
    ...
```

**Comment by mattsah** [comment]
Ok, that makes perfect sense now.  Yeah, I think making sure the numeric index doesn't appear (frankly not sure why it is appearing) and that it's sorted should solve this.

**Comment by mattsah** [comment]
I'll probably be able to get to it this weekend.

**Comment by janreges** [comment]
Awesome, thank you! It will help us and all other people with same development scenario.

Thank you for your job! :)

**Comment by janreges** [comment]
Hi Matthew, 

you've managed to look at it on the weekend? Probably not? :-))

Thank you.

**Comment by mattsah** [comment]
Hi @janreges 

Sorry about the delay.  This **should** be fixed in 1.0.5 -- I had a bit of difficulty trying to trigger it though.  I'm able to confirm the sort worked by doing a fresh install with 1.0.4 -- this didn't create the numeric keys as I think that occurs on updates, but it did create a package map where the packages were out of natural sort order.  I then specified the 1.0.5 release for opus and downgraded one of my other packages and confirmed the package map was sorted.

Sorting should reset keys at the same time, so this should solve the keys being strings.  Please try upgrading to 1.0.5 -- if you have no other opus packages that update, this won't fix the map up in itself, but you could try specifying a slightly lower version of an opus-package to force opus to run and cleanup the map, then re-upgrade after.

Let me know if that appears to:

1. Sort the package dependencies
2. Get rid of numeric indexes in the opus.map JSON

If that works for you, I'll close this.

**Comment by mattsah** [comment]
@janreges did this solve the issue?

**Comment by janreges** [comment]
Hi @mattsah,

thank you for your improvement - it works very well! :-)

Now, opus.map content is changed only when there was a real change in some files. Order in JSON arrays is more consistent and ready for versioning without unwanted conflicts.

Thank you very much! 👍
